### ISSUE TITLE
Lock Work Data from `header-localization` 

### ISSUE THREAD

**Issue by Afrokk** [CHIMEFRB/workflow#101]
## Description
We want to lock the work performed for certain events in the `header-localization` pipeline.

## Tasks
- [x] Find out which events are old (`Work["config"]=None`).
- [x] Convert old work objects to be compatible with the new system.
- [x] Lock new events.
- [x] Lock old events.

**Comment by Afrokk** [comment]
Locked events.

[header_loc_workflow_ids_to_lock_round2_31July2024.txt](https://github.com/user-attachments/files/16447626/header_loc_workflow_ids_to_lock_round2_31July2024.txt)
